// fitsverify-wasm — public TypeScript API.
//
// Runs NASA/HEASARC's fitsverify (via Demitri Muna's libfitsverify) entirely
// in the browser or Node, compiled to WebAssembly. No upload, no install,
// no backend: the FITS bytes never leave the page.
//
//   import { verifyFits } from 'fitsverify-wasm';
//   const report = await verifyFits(fileBytes);
//   if (!report.ok) report.messages.forEach(m => console.log(m.severity, m.text));

export type Severity = 'info' | 'warning' | 'error' | 'severe';

export interface FitsMessage {
  severity: Severity;
  /** libfitsverify error code (see fv_error_code). 0 for uncoded output. */
  code: number;
  /** 1-based HDU number the message refers to, or 0 for file-level. */
  hdu: number;
  text: string;
  /** Present only when `fixHints` is enabled: a targeted remediation hint. */
  fixHint?: string;
  /** Present only when `explain` is enabled: a longer explanation. */
  explain?: string;
}

export interface FitsReport {
  /** True iff the file is standard-conformant (0 errors, not aborted). */
  ok: boolean;
  numErrors: number;
  numWarnings: number;
  /** Header-Data Units processed. */
  numHdus: number;
  /** True if verification stopped early (e.g. fatal structural error). */
  aborted: boolean;
  /** Warnings + errors, in report order. (Info-level banner lines are omitted.) */
  messages: FitsMessage[];
  /** libfitsverify version string. */
  version: string;
}

export interface VerifyOptions {
  /** Attach a targeted fix hint to each message. Default false. */
  fixHints?: boolean;
  /** Attach a longer explanation to each message. Default false. */
  explain?: boolean;
  /** Verify the CHECKSUM/DATASUM keywords if present. Default false. */
  testChecksum?: boolean;
  /** Report errors only (suppress warnings). Default false. */
  errorsOnly?: boolean;
  /** Filename shown in the report (purely cosmetic). Default 'uploaded.fits'. */
  label?: string;
}

// The shape of the Emscripten module factory (generated by build.sh).
interface FvModule {
  ccall(
    name: string,
    returnType: string,
    argTypes: string[],
    args: unknown[],
  ): number;
  _malloc(n: number): number;
  _free(p: number): void;
  _fv_free(p: number): void;
  UTF8ToString(ptr: number): string;
  HEAPU8: Uint8Array;
}
type FvFactory = (opts?: Record<string, unknown>) => Promise<FvModule>;

let modulePromise: Promise<FvModule> | null = null;

/** Override how the .wasm binary is located (e.g. when serving from a CDN
 *  path that differs from the .mjs location). Call before the first
 *  verifyFits(). */
let wasmUrlOverride: string | undefined;
export function setWasmUrl(url: string): void {
  wasmUrlOverride = url;
}

async function getModule(): Promise<FvModule> {
  if (!modulePromise) {
    modulePromise = (async () => {
      // The generated glue is an ES module default-exporting the factory.
      // Bundlers resolve the relative import; the .wasm sits beside it.
      const mod = (await import('../dist/fitsverify.mjs')) as unknown as {
        default: FvFactory;
      };
      const opts: Record<string, unknown> = {};
      if (wasmUrlOverride) {
        opts.locateFile = (path: string) =>
          path.endsWith('.wasm') ? wasmUrlOverride! : path;
      }
      return mod.default(opts);
    })();
  }
  return modulePromise;
}

function toBytes(input: Uint8Array | ArrayBuffer): Uint8Array {
  return input instanceof Uint8Array ? input : new Uint8Array(input);
}

/** Verify a FITS file held in memory. Returns a structured conformance
 *  report. The bytes are validated locally — nothing is uploaded. */
export async function verifyFits(
  input: Uint8Array | ArrayBuffer,
  options: VerifyOptions = {},
): Promise<FitsReport> {
  const mod = await getModule();
  const bytes = toBytes(input);

  let optMask = 0;
  if (options.fixHints) optMask |= 0x1;
  if (options.explain) optMask |= 0x2;
  if (options.testChecksum) optMask |= 0x4;
  if (options.errorsOnly) optMask |= 0x8;

  const ptr = mod._malloc(bytes.length || 1);
  mod.HEAPU8.set(bytes, ptr);
  let resultPtr = 0;
  try {
    resultPtr = mod.ccall(
      'fv_verify_blob',
      'number',
      ['number', 'number', 'string', 'number'],
      [ptr, bytes.length, options.label ?? 'uploaded.fits', optMask],
    );
    const json = mod.UTF8ToString(resultPtr);
    return JSON.parse(json) as FitsReport;
  } finally {
    if (resultPtr) mod._fv_free(resultPtr);
    mod._free(ptr);
  }
}

/** The libfitsverify version compiled into the WASM module. */
export async function fitsverifyVersion(): Promise<string> {
  const mod = await getModule();
  const ptr = mod.ccall('fv_lib_version', 'number', [], []);
  return mod.UTF8ToString(ptr);
}
