// Golden-corpus regression test: run the built WASM module over a corpus of
// FITS files (valid + deliberately-malformed, generated by the upstream
// gen_test_fits.c) and assert the structured result matches golden.json.
//
// The golden values were produced from a differential run that confirmed the
// WASM build is byte-identical to the NATIVE libfitsverify across this corpus
// (counts AND message codes). This test guards against regressions in the
// WASM build, the C shim, or the TS wrapper.

import { describe, it, expect, beforeAll } from 'vitest';
import { readFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { verifyFits, fitsverifyVersion, type FitsReport } from '../src/index.ts';

const here = dirname(fileURLToPath(import.meta.url));
const corpusDir = join(here, 'corpus');
const golden = JSON.parse(readFileSync(join(here, 'golden.json'), 'utf8')) as Record<
  string,
  { ok: boolean; numErrors: number; numWarnings: number; numHdus: number; aborted: boolean; codes: number[] }
>;

describe('fitsverify-wasm — golden corpus', () => {
  beforeAll(async () => {
    // Warm the module once so the first per-file timing isn't the load cost.
    await fitsverifyVersion();
  });

  it('reports a non-empty libfitsverify version', async () => {
    const v = await fitsverifyVersion();
    expect(v).toMatch(/^\d+\.\d+/);
  });

  const files = readdirSync(corpusDir).filter((f) => f.endsWith('.fits')).sort();
  it('has a corpus and a golden entry for each file', () => {
    expect(files.length).toBeGreaterThan(0);
    for (const f of files) expect(golden[f], `golden entry for ${f}`).toBeDefined();
  });

  for (const f of files) {
    it(`matches golden for ${f}`, async () => {
      const bytes = new Uint8Array(readFileSync(join(corpusDir, f)));
      const r: FitsReport = await verifyFits(bytes, { label: f });
      const g = golden[f]!;
      expect(r.ok).toBe(g.ok);
      expect(r.numErrors).toBe(g.numErrors);
      expect(r.numWarnings).toBe(g.numWarnings);
      expect(r.numHdus).toBe(g.numHdus);
      expect(r.aborted).toBe(g.aborted);
      const codes = r.messages.map((m) => m.code).sort((a, b) => a - b);
      expect(codes).toEqual(g.codes);
    });
  }

  it('a valid file has ok=true and no actionable messages', async () => {
    const bytes = new Uint8Array(readFileSync(join(corpusDir, 'valid_minimal.fits')));
    const r = await verifyFits(bytes);
    expect(r.ok).toBe(true);
    expect(r.messages.length).toBe(0);
    expect(r.numHdus).toBe(1);
  });

  it('a structurally-broken file aborts with an error', async () => {
    const bytes = new Uint8Array(readFileSync(join(corpusDir, 'err_missing_end.fits')));
    const r = await verifyFits(bytes);
    expect(r.ok).toBe(false);
    expect(r.numErrors).toBeGreaterThanOrEqual(1);
    expect(r.aborted).toBe(true);
  });

  it('rejects empty input gracefully (not a FITS file)', async () => {
    const r = await verifyFits(new Uint8Array(0));
    expect(r.ok).toBe(false);
  });
});
