// Synthetic asteroid models for development & demo. These are NOT real DAMIT
// fits — they exist so the pipeline can be exercised end-to-end before real
// samples are wired in. The light curves below are *generated by the same
// forward model the viewer uses*, with optional Gaussian noise, so the
// observed–predicted overlay should always look consistent for these
// fixtures.

import type { AsteroidModel, LightCurve, ShapeModel, SpinState } from '../core/types.ts';
import { DEFAULT_SCATTERING } from '../core/types.ts';
import { buildFacetGeometry } from '../core/geometry.ts';
import { predictBrightness } from '../core/photometry.ts';

export function syntheticBrick(): AsteroidModel {
  const shape = brick(1.0, 0.45, 0.42); // elongated like a typical small asteroid
  return generated({
    name: '(demo) elongated brick',
    shape,
    spin: {
      poleLambdaDeg: 78,
      poleBetaDeg: 25,
      periodHours: 7.5,
      jd0: 2451545.0,
    },
    apparitions: [
      // One night, sun roughly toward −x_ecl, earth slightly off; α ≈ 8°.
      {
        nObs: 80,
        durationHours: 6,
        sun: { x: -0.95, y: -0.30, z: 0.08 },
        earth: { x: -1.78, y: -0.34, z: 0.05 },
        jdStart: 2451545.10,
        noiseFrac: 0.012,
      },
      // A different geometry (different solar elongation).
      {
        nObs: 65,
        durationHours: 5.5,
        sun: { x: -0.20, y: -0.96, z: 0.06 },
        earth: { x: -0.45, y: -1.81, z: 0.03 },
        jdStart: 2451810.20,
        noiseFrac: 0.018,
      },
    ],
    citation: 'Synthetic demo — replace with a real DAMIT model.',
  });
}

export function syntheticIcosphere(): AsteroidModel {
  // A near-spherical body produces a near-flat curve regardless of pole.
  return generated({
    name: '(demo) near-spherical body',
    shape: icosphereLike(),
    spin: {
      poleLambdaDeg: 0,
      poleBetaDeg: 90,
      periodHours: 6.0,
      jd0: 2451545.0,
    },
    apparitions: [
      {
        nObs: 60,
        durationHours: 5,
        sun: { x: -1.0, y: 0, z: 0 },
        earth: { x: -1.5, y: -0.4, z: 0 },
        jdStart: 2451545.0,
        noiseFrac: 0.005,
      },
    ],
    citation: 'Synthetic demo — sphere check, brightness should be nearly flat.',
  });
}

export function syntheticTumblingPotato(): AsteroidModel {
  // Bumpy three-axis ellipsoid — produces a non-symmetric curve.
  return generated({
    name: '(demo) bumpy ellipsoid',
    shape: deformedEllipsoid(),
    spin: {
      poleLambdaDeg: 210,
      poleBetaDeg: -55,
      periodHours: 11.27,
      jd0: 2451545.0,
    },
    apparitions: [
      {
        nObs: 100,
        durationHours: 8,
        sun: { x: 0.71, y: -0.70, z: 0.12 },
        earth: { x: 1.34, y: -1.32, z: 0.10 },
        jdStart: 2452000.0,
        noiseFrac: 0.020,
      },
    ],
    citation: 'Synthetic demo — bumpy ellipsoid, two unequal maxima per rotation.',
  });
}

interface Apparition {
  nObs: number;
  durationHours: number;
  sun: { x: number; y: number; z: number };
  earth: { x: number; y: number; z: number };
  jdStart: number;
  noiseFrac: number;
}

function generated(params: {
  name: string;
  shape: ShapeModel;
  spin: SpinState;
  apparitions: Apparition[];
  citation?: string;
}): AsteroidModel {
  const facets = buildFacetGeometry(params.shape);
  const rng = mulberry32(0xa1ce5d);
  const lcs: LightCurve[] = params.apparitions.map((app, i) => {
    const pts = [];
    for (let k = 0; k < app.nObs; k++) {
      const jd = app.jdStart + (k * app.durationHours) / 24 / Math.max(1, app.nObs - 1);
      const truth = predictBrightness(facets, params.spin, DEFAULT_SCATTERING, {
        jd,
        intensity: 0,
        sun: app.sun,
        earth: app.earth,
      });
      const noise = (rng() * 2 - 1) * app.noiseFrac * truth;
      pts.push({
        jd,
        intensity: truth + noise,
        sun: app.sun,
        earth: app.earth,
      });
    }
    return { id: i + 1, calibrated: false, points: pts };
  });
  return {
    name: params.name,
    shape: params.shape,
    spin: params.spin,
    lightCurves: lcs,
    scattering: { ...DEFAULT_SCATTERING },
    citation: params.citation,
  };
}

function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return (): number => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function brick(lx: number, ly: number, lz: number): ShapeModel {
  const hx = lx / 2, hy = ly / 2, hz = lz / 2;
  const verts = new Float32Array([
    -hx, -hy, -hz,  hx, -hy, -hz,  hx,  hy, -hz, -hx,  hy, -hz,
    -hx, -hy,  hz,  hx, -hy,  hz,  hx,  hy,  hz, -hx,  hy,  hz,
  ]);
  const q = (a: number, b: number, c: number, d: number): number[] => [a, b, c, a, c, d];
  const faces = new Uint32Array([
    ...q(0, 3, 2, 1), ...q(4, 5, 6, 7),
    ...q(0, 1, 5, 4), ...q(2, 3, 7, 6),
    ...q(1, 2, 6, 5), ...q(0, 4, 7, 3),
  ]);
  return { vertices: verts, faces };
}

function icosphereLike(): ShapeModel {
  // Sub-divided cube projected to a sphere; good enough for a flatness demo.
  const n = 14;
  const vs: number[] = [];
  const fs: number[] = [];
  const map = new Map<string, number>();
  const add = (x: number, y: number, z: number): number => {
    const l = Math.sqrt(x * x + y * y + z * z);
    const nx = x / l, ny = y / l, nz = z / l;
    const key = `${nx.toFixed(8)},${ny.toFixed(8)},${nz.toFixed(8)}`;
    let idx = map.get(key);
    if (idx === undefined) {
      idx = vs.length / 3;
      vs.push(nx, ny, nz);
      map.set(key, idx);
    }
    return idx;
  };
  const cubeFaces: ((i: number, j: number) => [number, number, number])[] = [
    (i, j) => [1, (2 * j) / n - 1, (2 * i) / n - 1],
    (i, j) => [-1, (2 * j) / n - 1, -((2 * i) / n - 1)],
    (i, j) => [(2 * j) / n - 1, 1, -((2 * i) / n - 1)],
    (i, j) => [(2 * j) / n - 1, -1, (2 * i) / n - 1],
    (i, j) => [-((2 * j) / n - 1), (2 * i) / n - 1, 1],
    (i, j) => [(2 * j) / n - 1, (2 * i) / n - 1, -1],
  ];
  for (const pt of cubeFaces) {
    for (let i = 0; i < n; i++) {
      for (let j = 0; j < n; j++) {
        const i0 = add(...pt(i, j));
        const i1 = add(...pt(i + 1, j));
        const i2 = add(...pt(i + 1, j + 1));
        const i3 = add(...pt(i, j + 1));
        fs.push(i0, i1, i2, i0, i2, i3);
      }
    }
  }
  return { vertices: new Float32Array(vs), faces: new Uint32Array(fs) };
}

function deformedEllipsoid(): ShapeModel {
  const ico = icosphereLike();
  const v = new Float32Array(ico.vertices);
  for (let i = 0; i < v.length; i += 3) {
    const x = v[i]!, y = v[i + 1]!, z = v[i + 2]!;
    // Ellipsoid axes.
    const ex = 1.0, ey = 0.58, ez = 0.42;
    // Two large bumps.
    const bump1 = 0.08 * Math.exp(-12 * ((x - 0.6) ** 2 + (y - 0.0) ** 2 + (z - 0.0) ** 2));
    const bump2 = 0.05 * Math.exp(-18 * ((x + 0.5) ** 2 + (y + 0.2) ** 2 + (z - 0.1) ** 2));
    const r = 1 + bump1 + bump2;
    v[i]     = ex * x * r;
    v[i + 1] = ey * y * r;
    v[i + 2] = ez * z * r;
  }
  return { vertices: v, faces: ico.faces };
}
